# # -- 코드를 입력하세요
# SELECT *
# FROM USER_INFO u LEFT JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
# ORDER BY o.SALES_DATE

SELECT YEAR(SALES_DATE) as YEAR,
    MONTH(SALES_DATE) as MONTH,
    COUNT(DISTINCT USER_ID) as PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) as PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID
                 FROM USER_INFO
                 WHERE YEAR(JOINED) = '2021')
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)