-- 코드를 입력하세요
SELECT i.NAME, i.DATETIME
FROM ANIMAL_INS i
    LEFT JOIN ANIMAL_OUTS o
    on i.ANIMAL_ID = o.ANIMAL_ID
WHERE o.ANIMAL_ID is null
order by DATEDIFF(i.DATETIME, o.DATETIME) DESC, i.DATETIME ASC
limit 3