SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(DATE_OF_BIRTH, '%Y-%m-%d') as date_of_birth
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH)=3
      AND (TLNO IS NOT NULL)
      AND GENDER ='W'
ORDER BY MEMBER_ID;