-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD b
    inner join USED_GOODS_USER u
    on b.WRITER_ID = u.USER_ID
where b.STATUS = 'DONE'
GROUP BY u.USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES

# SELECT * FROM USED_GOODS_BOARD
# where status = 'DONE'